version: '2'

services:
  gui:
#    image: moreillon/chartmuseum-gui:latest
# https://github.com/maximemoreillon/chartmuseum-gui/issues/1
    image: moreillon/chartmuseum-gui:3786d02d
    environment:
      PUBLIC_CHARTMUSEUM_URL: http://charter:8080
      PATH_BASE: "/gui"
#    ports:
#      - 3000:3000
    networks:
      - charter
  nginx:
    image: bitnami/nginx:1.23
    ports:
      - '80:8080'
    volumes:
      - /root/helmmeusum/charter.conf:/opt/bitnami/nginx/conf/server_blocks/charter.conf:ro
    networks:
      - charter

  minio:
    image: bitnami/minio:latest
#   image: localminio:2023.1
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
       - BITNAMI_DEBUG=true
       - MINIO_ROOT_USER=dummy
       - MINIO_ROOT_PASSWORD=dummy123
       - MINIO_DEFAULT_BUCKETS=dummy
       - MINIO_SCHEME=https
#       - MINIO_SKIP_CLIENT=yes
    volumes:
      - minio_data:/data
      - ./certs:/certs
    networks:
      - charter

  charter:
    image: bitnami/chartmuseum:latest
#    ports:
#     - '8080:8080'
    environment:
     - PORT=8080  
     - DEBUG=1
     - STORAGE=amazon
     - STORAGE_AMAZON_BUCKET=dummy
     - STORAGE_AMAZON_PREFIX=""
     - STORAGE_AMAZON_REGION=us-east-1
     - STORAGE_AMAZON_ENDPOINT=minio:9000
     - AWS_ACCESS_KEY_ID=dummy
     - AWS_SECRET_ACCESS_KEY=dummy123
     - AWS_INSECURE_SKIP_VERIFY=true
    networks:
      - charter

volumes:
  minio_data:
    driver: local
  charts:
    driver: local

networks:
  charter:
    external: true
